package com.index.field.service;

import com.cf.base.BaseFieldclass;

/**
 * Generated by JFinal.
 * create by yu_bo
 * 2019-03-25 10:50:39
 */
@SuppressWarnings("serial")
public class FieldClass extends BaseFieldclass<FieldClass> {
	//public static final FieldClass dao = new FieldClass().dao();

}