package com.cf.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFieldclass<M extends BaseFieldclass<M>> extends Model<M> implements IBean {

	public M setClassid(java.lang.Integer classid) {
		set("classid", classid);
		return (M)this;
	}
	
	public java.lang.Integer getClassid() {
		return getInt("classid");
	}

	public M setClassname(java.lang.String classname) {
		set("classname", classname);
		return (M)this;
	}
	
	public java.lang.String getClassname() {
		return getStr("classname");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setClassdesc(java.lang.String classdesc) {
		set("classdesc", classdesc);
		return (M)this;
	}
	
	public java.lang.String getClassdesc() {
		return getStr("classdesc");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
