package com.index.field.base;

/**
 * Generated by JFinal.
 * create by yu_bo
 * 2019-03-25 11:24:30
 */
@SuppressWarnings("serial")
public class FieldManager extends BaseFieldmanager<FieldManager> {
	//public static final FieldManager dao = new FieldManager().dao();

}