package com.cf;

import com.index.field.base.FieldManager;
import com.index.field.service.FieldClass;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingSet {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("fieldclass", "classid", FieldClass.class);
		arp.addMapping("fieldmanager", "id", FieldManager.class);
		

	}
}
